stages:
  - test


build:debian:
  stage: test
  image: registry.gitlab.com/treichl/cppargparse:latest
  tags:
    - gitlab-org
  script:
    - mkdir build
    - cd build
    - cmake -G"Ninja" -DCMAKE_BUILD_TYPE=Debug ..
    - ninja run_tests
