stages:
  - test


test:
  stage: test
  image: registry.gitlab.com/treichl/cppargparse:latest
  tags:
    - gitlab-org
  script:
    # configure build directory
    - mkdir build
    - cd build
    # configure coverage target
    - cmake -G"Ninja" -DCMAKE_BUILD_TYPE=Profiling ..
    # run coverage target
    - ninja coverage
    # build doxygen documentation
    - cd ..
    - doxygen
  artifacts:
    name: "cppargparse_${CI_COMMIT_BRANCH}${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - include/
      - docs/
    expire_in: 1000 yrs
