variables:
  CPPARGPARSE_ARTIFACT_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}"
  DOCKER_IMAGE_PREFIX: docker:23.0.6


stages:
  - docker
  - test
  - deploy


docker:
  stage: docker
  image: ${DOCKER_IMAGE_PREFIX}-git
  tags:
    - docker
  services:
    - ${DOCKER_IMAGE_PREFIX}-dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE} docker
    - docker push ${CI_REGISTRY_IMAGE}
  # only build the image if the following variable is set
  rules:
    - if: $CPPARGPARSE_DOCKER


test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}
  tags:
    - gitlab-org
  script:
    # configure build directory
    - mkdir build
    - cd build
    # configure coverage target
    - cmake -G"Ninja" -DCMAKE_BUILD_TYPE=Profiling ..
    # run coverage target
    - ninja coverage
    # go back to source dir
    - cd ${CI_PROJECT_DIR}
    # gcovr: cobertura
    - mkdir -p docs/coverage
    - gcovr --filter include --branches --exclude-unreachable-branches --print-summary --cobertura-pretty -o docs/coverage/cobertura.xml
    # gcovr: html
    - gcovr --filter include --branches --exclude-unreachable-branches --html-details docs/coverage/index.html
    # build doxygen documentation
    - doxygen
  coverage: /^\s*branches:\s*\d+.\d+\%/
  artifacts:
    name: ${CPPARGPARSE_ARTIFACT_NAME}
    paths:
      - include/
      - docs/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: docs/coverage/cobertura.xml
    expire_in: 1000 yrs


pages:
  stage: deploy
  image: ${CI_REGISTRY_IMAGE}
  tags:
    - gitlab-org
  dependencies:
    - test
  script:
    - mv docs public
  artifacts:
    paths:
      - public
