variables:
  CPPARGPARSE_ARTIFACT_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}"
  DOCKER_IMAGE_PREFIX: docker:23.0.6


stages:
  - docker
  - test


docker:
  stage: docker
  image: ${DOCKER_IMAGE_PREFIX}-git
  tags:
    - docker
  services:
    - ${DOCKER_IMAGE_PREFIX}-dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE} docker
    - docker push ${CI_REGISTRY_IMAGE}
  # only build the image if the following variable is set
  rules:
    - if: $CPPARGPARSE_DOCKER


test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}
  tags:
    - gitlab-org
  script:
    # configure build directory
    - mkdir build
    - cd build
    # configure coverage target
    - cmake -G"Ninja" -DCMAKE_BUILD_TYPE=Profiling ..
    # run coverage target
    - ninja coverage
    # build doxygen documentation
    - cd ..
    - doxygen
  artifacts:
    name: ${CPPARGPARSE_ARTIFACT_NAME}
    paths:
      - include/
      - docs/
    expire_in: 1000 yrs
